#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

 npm test
#protected_branch='master'
#current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
#
#if [ "${current_branch}" = $protected_branch ]; then
#    npm run build
#    exit 0
#else
#    exit 0
#fi
